### ISSUE TITLE
Error when sending OTP

### ISSUE THREAD

**Issue by AndoSantara** [faytranevozter/zenziva-go-sms#1]
i got an issue when try send otp

here is the error message
{0 0822xxxxx false Wrong Parameter}

any suggestion ?

Thanks

**Comment by faytranevozter** [comment]
i think zenziva change the results, the `id` was integer, and now become string

**Comment by faytranevozter** [comment]
I'm sorry i was misreading your issue. Currenly this library only support account type "masking", i guess your account is regular. if so, im sorry we're not support yet for regular account

**Comment by AndoSantara** [comment]
sorry my bad , i used wrong type for masking. lol
now it's solved , thanks
